[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BrightEyes-TTM"
authors = [{name = "Fondazione Istituto Italiano di Tecnologia", email = "giuseppe.vicidomini@iit.it"}]
dynamic = ["version", "description"]
